"""
Seed data for Prozis supplement products.
Generated from product URLs - Prozis.com returned 429/403/timeouts during fetch,
so data uses product names, Open Food Facts, and reasonable defaults.
"""

PROZIS_PRODUCTS = [
    {
        "name": "Creatina Creapure",
        "brand": "Prozis",
        "description": "100% pure creatine monohydrate with Creapure seal. Designed for high-intensity strength training and muscle performance.",
        "category": "rendimiento",
        "serving_size": 3.0,
        "serving_unit": "g",
        "calories": 0.0,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 0.0,
        "usage_instructions": "Add 4 level scoops (3g) to 200-250 ml of water. Take 1 dose daily.",
        "warnings": "May contain traces of milk, soy, egg, and gluten. Intended for adults only. Consult a doctor if pregnant or breastfeeding.",
        "image_url": None,
        "purchase_url": "https://prozis.com/KrRD",
    },
    {
        "name": "100% Real Whey Protein",
        "brand": "Prozis",
        "description": "Premium whey protein concentrate for muscle building and recovery. Made in the EU.",
        "category": "proteina",
        "serving_size": 30.0,
        "serving_unit": "g",
        "calories": 118.0,
        "protein": 22.8,
        "carbs": 1.0,
        "fat": 2.55,
        "usage_instructions": "Mix 1 scoop (30g) with 250-300ml water or milk. Consume post-workout or as needed.",
        "warnings": "Contains milk. May contain traces of eggs, gluten, soy.",
        "image_url": None,
        "purchase_url": "https://prozis.com/1MbKn",
    },
    {
        "name": "Whey Protein Isolated Zero",
        "brand": "Prozis",
        "description": "Whey protein isolate with zero sugar and low carbs. Ideal for lean muscle gain and weight management.",
        "category": "proteina",
        "serving_size": 30.0,
        "serving_unit": "g",
        "calories": 110.0,
        "protein": 24.0,
        "carbs": 0.5,
        "fat": 0.5,
        "usage_instructions": "Mix 1 scoop (30g) with 250-300ml water or milk. Best consumed post-workout.",
        "warnings": "Contains milk. May contain traces of eggs, gluten, soy.",
        "image_url": None,
        "purchase_url": "https://prozis.com/1JZKS",
    },
    {
        "name": "Multi PRZ 60 caps",
        "brand": "Prozis",
        "description": "Multivitamin complex for athletes - comprehensive vitamin and mineral formula for overall health and performance.",
        "category": "vitaminas",
        "serving_size": 1.0,
        "serving_unit": "capsule",
        "calories": None,
        "protein": None,
        "carbs": None,
        "fat": None,
        "usage_instructions": "Take 1 capsule daily with a meal.",
        "warnings": None,
        "image_url": None,
        "purchase_url": "https://prozis.com/HYT7",
    },
    {
        "name": "Omega 3",
        "brand": "Prozis",
        "description": "Omega 3 fatty acids (EPA and DHA) for heart health, brain function, and inflammation support.",
        "category": "salud",
        "serving_size": 1.0,
        "serving_unit": "softgel",
        "calories": None,
        "protein": None,
        "carbs": None,
        "fat": None,
        "usage_instructions": "Take 1-2 softgels daily with a meal.",
        "warnings": None,
        "image_url": None,
        "purchase_url": "https://prozis.com/1BnyS",
    },
    {
        "name": "Vitamina C",
        "brand": "Prozis",
        "description": "Vitamin C supplement for immune support, antioxidant protection, and collagen synthesis.",
        "category": "vitaminas",
        "serving_size": 1.0,
        "serving_unit": "tablet",
        "calories": None,
        "protein": None,
        "carbs": None,
        "fat": None,
        "usage_instructions": "Take 1 tablet daily with water.",
        "warnings": None,
        "image_url": None,
        "purchase_url": "https://prozis.com/1N7hY",
    },
    {
        "name": "Vitamin D3 2000 IU",
        "brand": "Prozis",
        "description": "Vitamin D3 2000 IU in softgel form for bone health, immune function, and calcium absorption.",
        "category": "vitaminas",
        "serving_size": 1.0,
        "serving_unit": "softgel",
        "calories": None,
        "protein": None,
        "carbs": None,
        "fat": None,
        "usage_instructions": "Take 1 softgel daily with a meal.",
        "warnings": None,
        "image_url": None,
        "purchase_url": "https://prozis.com/1N7j8",
    },
    {
        "name": "ZMA",
        "brand": "Prozis",
        "description": "Zinc, Magnesium and Vitamin B6 formula for recovery, sleep quality, and muscle function.",
        "category": "minerales",
        "serving_size": 2.0,
        "serving_unit": "capsules",
        "calories": None,
        "protein": None,
        "carbs": None,
        "fat": None,
        "usage_instructions": "Take 2 capsules 30-60 minutes before bed on an empty stomach.",
        "warnings": None,
        "image_url": None,
        "purchase_url": "https://prozis.com/1N7cf",
    },
    {
        "name": "EEAA Amino Acids",
        "brand": "Prozis",
        "description": "Essential amino acids (EAA) for muscle protein synthesis, recovery, and endurance.",
        "category": "aminoacidos",
        "serving_size": 10.0,
        "serving_unit": "g",
        "calories": 40.0,
        "protein": 10.0,
        "carbs": 0.0,
        "fat": 0.0,
        "usage_instructions": "Mix 1 scoop (10g) with 300ml water. Take during or after training.",
        "warnings": None,
        "image_url": None,
        "purchase_url": "https://prozis.com/1tHwl",
    },
    {
        "name": "Avena Instantánea (Polvo)",
        "brand": "Prozis",
        "description": "Instant oat powder for easy preparation. Source of complex carbohydrates and fiber.",
        "category": "carbohidratos",
        "serving_size": 50.0,
        "serving_unit": "g",
        "calories": 195.0,
        "protein": 6.5,
        "carbs": 33.0,
        "fat": 3.5,
        "usage_instructions": "Mix 50g with 150-200ml hot water or milk. Stir and let sit 1-2 minutes.",
        "warnings": "May contain gluten.",
        "image_url": None,
        "purchase_url": "https://prozis.com/1N7f4",
    },
    {
        "name": "Harina de Arroz (Rice Porridge)",
        "brand": "Prozis",
        "description": "Rice flour/porridge for gluten-free carbohydrates. Ideal for pre-workout or meal replacement.",
        "category": "carbohidratos",
        "serving_size": 50.0,
        "serving_unit": "g",
        "calories": 185.0,
        "protein": 3.5,
        "carbs": 40.0,
        "fat": 0.5,
        "usage_instructions": "Mix with water or milk. Cook or consume as porridge. Can be added to shakes.",
        "warnings": None,
        "image_url": None,
        "purchase_url": "https://prozis.com/1rn6G",
    },
    {
        "name": "Arroz Inflado",
        "brand": "Prozis",
        "description": "Puffed rice for light, crunchy carbohydrates. Low in fat, versatile for snacks and recipes.",
        "category": "carbohidratos",
        "serving_size": 30.0,
        "serving_unit": "g",
        "calories": 120.0,
        "protein": 2.5,
        "carbs": 26.0,
        "fat": 0.5,
        "usage_instructions": "Use as cereal with milk, in protein bars, or as a snack.",
        "warnings": None,
        "image_url": None,
        "purchase_url": "https://prozis.com/1bkYD",
    },
    {
        "name": "Quema Grasas Xcess",
        "brand": "Prozis",
        "description": "Thermogenic fat burner formula to support metabolism and energy during training.",
        "category": "quemadores",
        "serving_size": 1.0,
        "serving_unit": "serving",
        "calories": None,
        "protein": None,
        "carbs": None,
        "fat": None,
        "usage_instructions": "Take as directed on label. Typically 1 serving in the morning or before training.",
        "warnings": "Contains caffeine. Not suitable for pregnant/breastfeeding. Consult doctor if taking medications.",
        "image_url": None,
        "purchase_url": "https://prozis.com/FTTy",
    },
    {
        "name": "Diuretic Plus (Viales)",
        "brand": "Prozis",
        "description": "Liquid diuretic formula in vials for water retention management before events or photoshoots.",
        "category": "otros",
        "serving_size": 1.0,
        "serving_unit": "vial",
        "calories": None,
        "protein": None,
        "carbs": None,
        "fat": None,
        "usage_instructions": "Take 1 vial as directed. Typically used 1-2 days before target date.",
        "warnings": "Diuretic. Stay hydrated. Consult doctor if you have kidney or heart conditions.",
        "image_url": None,
        "purchase_url": "https://prozis.com/1mTDm",
    },
    {
        "name": "Diuretic Complex (Cápsulas)",
        "brand": "Prozis",
        "description": "Capsule-form diuretic with natural ingredients for water balance support.",
        "category": "otros",
        "serving_size": 1.0,
        "serving_unit": "capsule",
        "calories": None,
        "protein": None,
        "carbs": None,
        "fat": None,
        "usage_instructions": "Take as directed on label with plenty of water.",
        "warnings": "Diuretic. Stay hydrated. Consult doctor if you have kidney or heart conditions.",
        "image_url": None,
        "purchase_url": "https://prozis.com/1x7Kf",
    },
    {
        "name": "Apetite Control",
        "brand": "Prozis",
        "description": "Appetite control supplement to support weight management and reduce cravings.",
        "category": "salud",
        "serving_size": 1.0,
        "serving_unit": "capsule",
        "calories": None,
        "protein": None,
        "carbs": None,
        "fat": None,
        "usage_instructions": "Take 1-2 capsules before main meals as directed.",
        "warnings": None,
        "image_url": None,
        "purchase_url": "https://prozis.com/1L2x5",
    },
    {
        "name": "Magnesio Bisglicinato",
        "brand": "Prozis",
        "description": "Magnesium bisglycinate for improved absorption. Supports muscle function, relaxation, and sleep.",
        "category": "minerales",
        "serving_size": 1.0,
        "serving_unit": "capsule",
        "calories": None,
        "protein": None,
        "carbs": None,
        "fat": None,
        "usage_instructions": "Take 1-2 capsules daily, preferably in the evening.",
        "warnings": None,
        "image_url": None,
        "purchase_url": "https://prozis.com/1N7gJ",
    },
    {
        "name": "Probiótico",
        "brand": "Prozis",
        "description": "Probiotic supplement for digestive health and gut flora support.",
        "category": "salud",
        "serving_size": 1.0,
        "serving_unit": "capsule",
        "calories": None,
        "protein": None,
        "carbs": None,
        "fat": None,
        "usage_instructions": "Take 1 capsule daily on an empty stomach, preferably in the morning.",
        "warnings": "Refrigerate after opening if indicated.",
        "image_url": None,
        "purchase_url": "https://prozis.com/1N7jf",
    },
    {
        "name": "Peanut Butter",
        "brand": "Prozis",
        "description": "100% peanut butter. High in protein and healthy fats. No added sugar.",
        "category": "carbohidratos",
        "serving_size": 30.0,
        "serving_unit": "g",
        "calories": 180.0,
        "protein": 8.0,
        "carbs": 6.0,
        "fat": 15.0,
        "usage_instructions": "Spread on bread, add to shakes, or eat by the spoon. Store in a cool, dry place.",
        "warnings": "Contains peanuts. May contain traces of other nuts.",
        "image_url": None,
        "purchase_url": "https://prozis.com/Mg69",
    },
    {
        "name": "Almond Butter",
        "brand": "Prozis",
        "description": "100% almond butter. Rich in healthy fats, vitamin E, and protein.",
        "category": "carbohidratos",
        "serving_size": 30.0,
        "serving_unit": "g",
        "calories": 175.0,
        "protein": 6.0,
        "carbs": 5.0,
        "fat": 15.0,
        "usage_instructions": "Spread on bread, add to shakes, or eat by the spoon. Store in a cool, dry place.",
        "warnings": "Contains almonds. May contain traces of other nuts.",
        "image_url": None,
        "purchase_url": "https://prozis.com/1N7jK",
    },
    {
        "name": "Aloe Vera",
        "brand": "Prozis",
        "description": "Aloe vera supplement for digestive health, skin support, and internal wellness.",
        "category": "salud",
        "serving_size": None,
        "serving_unit": None,
        "calories": None,
        "protein": None,
        "carbs": None,
        "fat": None,
        "usage_instructions": "Take as directed on label.",
        "warnings": None,
        "image_url": None,
        "purchase_url": "https://prozis.com/1LHnY",
    },
]
