"""
Unified file storage via Cloudflare R2 (S3-compatible API).

Two **private** buckets – NO public access.  All reads go through presigned
URLs generated by the backend, which enforces authentication and authorization.

trackfiz-platform  (R2_PLATFORM_BUCKET)
  Global, system-level assets shared across all workspaces.
  Structure:
    exercises/{id}.png
    foods/{id}.png
    supplements/{id}.png

trackfiz-workspaces  (R2_WORKSPACES_BUCKET)
  Per-workspace content following a strict hierarchy:
    w/{workspace_id}/branding/{file}
    w/{workspace_id}/trainers/{user_id}/avatar/{file}
    w/{workspace_id}/clients/{client_id}/avatar/{file}
    w/{workspace_id}/clients/{client_id}/progress-photos/{file}
    w/{workspace_id}/clients/{client_id}/documents/{file}
    w/{workspace_id}/exercises/{file}
    w/{workspace_id}/recipes/{file}
    w/{workspace_id}/lms/{file}
"""
import asyncio
import time
import uuid as _uuid
import logging
from functools import partial
from typing import Optional

import boto3
from botocore.config import Config as BotoConfig

from app.core.config import settings

logger = logging.getLogger(__name__)

_s3_client = None

PLATFORM_PRESIGN_TTL = 3600      # 1 hour for system assets (cached by browser)
WORKSPACE_PRESIGN_TTL = 900      # 15 min for user-generated content

# Cache en memoria de URLs firmadas. Las respuestas de un endpoint que devuelve
# 100 ejercicios hacían 200 presigns; ahora con cache reusamos la URL durante
# la mitad del TTL (margen de seguridad frente a drift) y evitamos el
# `run_in_executor` por entrada. Mapa: (bucket, key) -> (url, expires_epoch).
_PRESIGN_CACHE: dict[tuple[str, str], tuple[str, float]] = {}
_PRESIGN_CACHE_MAX = 4096
_PRESIGN_CACHE_RATIO = 0.5       # reutilizamos la URL como mucho TTL * ratio


def _get_s3():
    global _s3_client
    if _s3_client is None:
        if not settings.R2_ACCOUNT_ID:
            raise RuntimeError(
                "R2_ACCOUNT_ID is not configured. Set it in environment variables."
            )
        _s3_client = boto3.client(
            "s3",
            endpoint_url=f"https://{settings.R2_ACCOUNT_ID}.r2.cloudflarestorage.com",
            aws_access_key_id=settings.R2_ACCESS_KEY_ID,
            aws_secret_access_key=settings.R2_SECRET_ACCESS_KEY,
            config=BotoConfig(signature_version="s3v4"),
            region_name="auto",
        )
    return _s3_client


def _sync_put(bucket: str, key: str, body: bytes, content_type: str):
    _get_s3().put_object(Bucket=bucket, Key=key, Body=body, ContentType=content_type)


def _sync_delete(bucket: str, key: str):
    _get_s3().delete_object(Bucket=bucket, Key=key)


def _sync_presign(bucket: str, key: str, ttl: int) -> str:
    return _get_s3().generate_presigned_url(
        "get_object",
        Params={"Bucket": bucket, "Key": key},
        ExpiresIn=ttl,
    )


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------

def generate_filename(original_filename: Optional[str] = None) -> str:
    """Generate a unique filename preserving the original extension."""
    ext = "bin"
    if original_filename and "." in original_filename:
        ext = original_filename.rsplit(".", 1)[-1].lower()
    return f"{_uuid.uuid4()}.{ext}"


_PLATFORM_TOP_LEVELS: tuple[str, ...] = (
    "exercises/",
    "foods/",
    "supplements/",
    # Plantillas y otros recursos globales por carpeta de primer nivel.
    # Si en el futuro añadimos otra carpeta nueva, solo hay que sumarla aqui
    # para que los walkers de R2 reconozcan tanto las URLs canonicas como
    # las firmadas (que vienen del endpoint S3 de R2).
)


def platform_key_from_url(url: str) -> Optional[str]:
    """Extract the R2 key from a full platform URL.

    Acepta tres formatos:
      1. Canonical (custom domain): ``{R2_PLATFORM_PUBLIC_URL}/exercises/foo.png``
      2. Presigned (R2 endpoint): ``https://{acc}.r2.cloudflarestorage.com/{bucket}/exercises/foo.png?X-Amz-...``
      3. Cualquier URL que contenga ``/exercises/``, ``/foods/``,
         ``/supplements/`` (las carpetas top-level del bucket platform).

    Devolvemos solo la key relativa al bucket, sin querystring.
    """
    prefix = f"{settings.R2_PLATFORM_PUBLIC_URL}/"
    if url.startswith(prefix):
        return url[len(prefix):].split("?")[0]

    base = url.split("?", 1)[0]
    for top in _PLATFORM_TOP_LEVELS:
        marker = f"/{top}"
        idx = base.rfind(marker)
        if idx >= 0:
            return base[idx + 1:]
    return None


def workspace_key_from_url(url: str) -> Optional[str]:
    """Extract the R2 key from a full workspace URL.

    Acepta el dominio personalizado ``{R2_WORKSPACES_PUBLIC_URL}/w/...`` y
    cualquier URL (incluida la firmada del endpoint S3) que contenga
    ``/w/{workspace_id}/...``.
    """
    prefix = f"{settings.R2_WORKSPACES_PUBLIC_URL}/"
    if url.startswith(prefix):
        return url[len(prefix):].split("?")[0]
    base = url.split("?", 1)[0]
    idx = base.rfind("/w/")
    if idx >= 0:
        return base[idx + 1:]
    return None


# ---------------------------------------------------------------------------
# Presigned URL generation  (the primary read-path)
# ---------------------------------------------------------------------------

def _cache_get(bucket: str, key: str) -> Optional[str]:
    entry = _PRESIGN_CACHE.get((bucket, key))
    if entry is None:
        return None
    url, expires = entry
    if expires <= time.monotonic():
        _PRESIGN_CACHE.pop((bucket, key), None)
        return None
    return url


def _cache_set(bucket: str, key: str, url: str, ttl: int) -> None:
    if len(_PRESIGN_CACHE) >= _PRESIGN_CACHE_MAX:
        # Eviction simple: borra el 25% más antiguo.
        now = time.monotonic()
        stale = [k for k, (_, exp) in _PRESIGN_CACHE.items() if exp <= now]
        for k in stale:
            _PRESIGN_CACHE.pop(k, None)
        if len(_PRESIGN_CACHE) >= _PRESIGN_CACHE_MAX:
            victims = sorted(_PRESIGN_CACHE.items(), key=lambda kv: kv[1][1])[: _PRESIGN_CACHE_MAX // 4]
            for k, _ in victims:
                _PRESIGN_CACHE.pop(k, None)
    _PRESIGN_CACHE[(bucket, key)] = (url, time.monotonic() + ttl * _PRESIGN_CACHE_RATIO)


async def presign_platform_url(key: str) -> str:
    """Generate a time-limited presigned URL for a platform asset.

    `generate_presigned_url` de boto3 **no hace I/O**: sólo construye la URL y
    firma con HMAC-SHA256 en memoria. Por eso se ejecuta en el loop (sin
    run_in_executor) — así evitamos saturar el ThreadPoolExecutor por defecto
    cuando una respuesta firma 200+ URLs a la vez (esto antes provocaba picos
    de +2s en /workouts/exercises en cold-start).
    """
    bucket = settings.R2_PLATFORM_BUCKET
    cached = _cache_get(bucket, key)
    if cached is not None:
        return cached
    url = _sync_presign(bucket, key, PLATFORM_PRESIGN_TTL)
    _cache_set(bucket, key, url, PLATFORM_PRESIGN_TTL)
    return url


async def presign_workspace_url(key: str) -> str:
    """Generate a time-limited presigned URL for a workspace asset.

    Ver nota de :func:`presign_platform_url`: la firma es CPU-bound ligera y
    síncrona; ejecutarla sin hop al executor es más rápido y no bloquea el
    event loop de forma apreciable.
    """
    bucket = settings.R2_WORKSPACES_BUCKET
    cached = _cache_get(bucket, key)
    if cached is not None:
        return cached
    url = _sync_presign(bucket, key, WORKSPACE_PRESIGN_TTL)
    _cache_set(bucket, key, url, WORKSPACE_PRESIGN_TTL)
    return url


def platform_url(key: str) -> str:
    """Build reference URL for the platform bucket (stored in DB).
    Note: these URLs are NOT directly accessible – the backend resolves them
    to presigned URLs before sending to the client.
    """
    return f"{settings.R2_PLATFORM_PUBLIC_URL}/{key}"


def workspace_url(key: str) -> str:
    """Build reference URL for the workspaces bucket (stored in DB)."""
    return f"{settings.R2_WORKSPACES_PUBLIC_URL}/{key}"


# ---------------------------------------------------------------------------
# Platform bucket  (global system assets)
# ---------------------------------------------------------------------------

async def upload_platform_asset(
    content: bytes,
    key: str,
    content_type: str = "image/png",
) -> str:
    """Upload a global platform asset (exercise image, food photo, etc.)."""
    loop = asyncio.get_running_loop()
    try:
        await loop.run_in_executor(
            None,
            partial(_sync_put, settings.R2_PLATFORM_BUCKET, key, content, content_type),
        )
    except Exception:
        logger.exception("R2 platform upload failed key=%s", key)
        raise
    return platform_url(key)


# ---------------------------------------------------------------------------
# Workspace bucket  (per-workspace user content)
# ---------------------------------------------------------------------------

def _ws_key(workspace_id, *parts: str) -> str:
    """Build a workspace-scoped key: w/{workspace_id}/parts..."""
    return f"w/{workspace_id}/{'/'.join(parts)}"


async def upload_workspace_file(
    content: bytes,
    workspace_id,
    *path_parts: str,
    content_type: str = "application/octet-stream",
) -> str:
    """Upload a file scoped to a workspace."""
    key = _ws_key(workspace_id, *path_parts)
    loop = asyncio.get_running_loop()
    try:
        await loop.run_in_executor(
            None,
            partial(_sync_put, settings.R2_WORKSPACES_BUCKET, key, content, content_type),
        )
    except Exception:
        logger.exception("R2 workspace upload failed key=%s", key)
        raise
    return workspace_url(key)


async def delete_workspace_file(workspace_id, *path_parts: str) -> None:
    """Delete a file from the workspace bucket."""
    key = _ws_key(workspace_id, *path_parts)
    loop = asyncio.get_running_loop()
    try:
        await loop.run_in_executor(
            None,
            partial(_sync_delete, settings.R2_WORKSPACES_BUCKET, key),
        )
    except Exception:
        logger.exception("R2 workspace delete failed key=%s", key)


# ---------------------------------------------------------------------------
# Batch URL resolver  (for API responses)
# ---------------------------------------------------------------------------

async def resolve_url(url: Optional[str]) -> Optional[str]:
    """Convert a stored R2 reference URL to a presigned URL.
    Returns None or the original value when it's not an R2 URL.
    """
    if not url:
        return url
    platform_base = settings.R2_PLATFORM_PUBLIC_URL
    workspace_base = settings.R2_WORKSPACES_PUBLIC_URL
    if url.startswith(platform_base):
        key = platform_key_from_url(url)
        if key:
            return await presign_platform_url(key)
    elif url.startswith(workspace_base):
        key = workspace_key_from_url(url)
        if key:
            return await presign_workspace_url(key)
    return url


async def resolve_urls(urls: list[Optional[str]]) -> list[Optional[str]]:
    """Batch-resolve multiple R2 reference URLs."""
    return list(await asyncio.gather(*(resolve_url(u) for u in urls)))


# ---------------------------------------------------------------------------
# Walker para JSONB (programa de entrenamiento, plan nutricional, etc.)
# ---------------------------------------------------------------------------

# Campos que tipicamente guardan URLs de R2 dentro de los snapshots JSONB
# (template del programa, plan nutricional, ejercicios anidados...).
# Si encuentras algun campo nuevo, simplemente anadelo a esta tupla.
_IMAGE_URL_FIELDS: tuple[str, ...] = (
    "image_url",
    "thumbnail_url",
    "imageUrl",
    "thumbnailUrl",
    "photo_url",
    "avatar_url",
)


def _is_r2_url(url: str) -> bool:
    if not url:
        return False
    if url.startswith(settings.R2_PLATFORM_PUBLIC_URL):
        return True
    if url.startswith(settings.R2_WORKSPACES_PUBLIC_URL):
        return True
    base = url.split("?", 1)[0]
    if "/w/" in base:
        return True
    for top in _PLATFORM_TOP_LEVELS:
        if f"/{top}" in base:
            return True
    return False


def _normalize_to_canonical(url: Optional[str]) -> Optional[str]:
    """Devuelve la URL canonica (sin querystring) si reconocemos la key.

    La idea es que en BBDD guardemos la canonica (que no caduca) y solo
    presigneemos en el momento de servir al cliente. Si la URL no es de R2
    o no la reconocemos, la devolvemos tal cual para no romper nada.
    """
    if not url:
        return url
    if not _is_r2_url(url):
        return url
    key = platform_key_from_url(url)
    if key is not None:
        return platform_url(key)
    key = workspace_key_from_url(url)
    if key is not None:
        return workspace_url(key)
    return url


def _walk_collect_image_urls(node, acc: list[str]) -> None:
    if isinstance(node, dict):
        for k, v in node.items():
            if k in _IMAGE_URL_FIELDS and isinstance(v, str) and v:
                if _is_r2_url(v):
                    acc.append(v)
            else:
                _walk_collect_image_urls(v, acc)
    elif isinstance(node, list):
        for v in node:
            _walk_collect_image_urls(v, acc)


def _walk_replace_image_urls(node, mapping: dict[str, str]) -> None:
    if isinstance(node, dict):
        for k, v in list(node.items()):
            if k in _IMAGE_URL_FIELDS and isinstance(v, str) and v in mapping:
                node[k] = mapping[v]
            else:
                _walk_replace_image_urls(v, mapping)
    elif isinstance(node, list):
        for v in node:
            _walk_replace_image_urls(v, mapping)


async def resolve_image_urls_in_obj(obj):
    """Recorre un dict/list (e.g. ``template`` JSONB) y refirma cada URL R2.

    Idempotente y seguro: se aplica solo a campos cuyo nombre figura en
    ``_IMAGE_URL_FIELDS`` y solo cuando la URL parece de R2. Devuelve el
    mismo objeto mutado *in place* (mas la lista resuelta) para que el
    caller pueda asignarlo directamente al response. Hacemos batching:
    presignamos en un solo gather, sin romper el event loop con N hops.
    """
    if obj is None:
        return obj
    urls: list[str] = []
    _walk_collect_image_urls(obj, urls)
    if not urls:
        return obj
    # Deduplicamos para no firmar varias veces la misma URL en el mismo
    # response. Mantiene el orden estable.
    unique = list(dict.fromkeys(urls))
    resolved = await asyncio.gather(*(resolve_url(u) for u in unique))
    mapping = {orig: new for orig, new in zip(unique, resolved) if new}
    _walk_replace_image_urls(obj, mapping)
    return obj


def normalize_image_urls_in_obj(obj):
    """Convierte cada ``image_url`` R2 dentro del objeto a su forma canonica.

    Util al GUARDAR el JSONB del template: nos quedamos con la URL sin
    querystring, asi cuando lo leemos podemos refirmar de cero sin
    arrastrar firmas caducadas. Mutamos in place y devolvemos el objeto.
    """
    if obj is None:
        return obj

    def _walk(node):
        if isinstance(node, dict):
            for k, v in list(node.items()):
                if k in _IMAGE_URL_FIELDS and isinstance(v, str) and v:
                    canonical = _normalize_to_canonical(v)
                    if canonical != v:
                        node[k] = canonical
                else:
                    _walk(v)
        elif isinstance(node, list):
            for v in node:
                _walk(v)

    _walk(obj)
    return obj
